# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# To configure individual guides, please use the _data/guides.yml file.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 18F Guides home
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Looking for U.S. government information and services? Visit USA.gov
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
designurl: https://designsystem.digital.gov
twitter_username: jekyllrb
github_username: jekyll
agency_primary: GSA
agency_secondary: TTS
guide_label: Guide
guide_cta: Visit the Guide

# Build settings
plugins:
  - jekyll-feed

# Collections
collections_dir: guides
collections:
  accessibility:
    output: true
    permalink: /:collection/:path/ # trailing forward slash generates an index.html
  agile:
    output: true
    permalink: /:collection/:path/
  brand:
    output: true
    permalink: /:collection/:path/
  content:
    output: true
    permalink: /:collection/:path/
  derisking:
    output: true
    permalink: /:collection/:path/
  engineering:
    output: true
    permalink: /:collection/:path/
  product:
    output: true
    permalink: /:collection/:path/
  ux:
    output: true
    permalink: /:collection/:path/
# Page defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: page
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
