banner:
  header: An official website of the United States government
  action: "Here’s how you know"
  flag: "U.S. flag"
  official: "<strong>Official websites use .gov</strong><br />A
    <strong>.gov</strong> website belongs to an official government
    organization in the United States."
  secure: '<strong>Secure .gov websites use HTTPS</strong><br />A
    <strong>lock</strong> (
    <span class="icon-lock"><svg xmlns="http://www.w3.org/2000/svg" width="52" height="64" viewBox="0 0 52 64"
    class="usa-banner__lock-image" role="img"
    aria-labelledby="banner-lock-title-default banner-lock-description-default" focusable="false">
    <title id="banner-lock-title-default">Lock</title>
    <desc id="banner-lock-description-default">A locked padlock</desc>
    <path fill="#000000" fill-rule="evenodd"
    d="M26 0c10.493 0 19 8.507 19 19v9h3a4 4 0 0 1 4 4v28a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V32a4 4 0 0 1 4-4h3v-9C7 8.507 15.507 0 26 0zm0 8c-5.979 0-10.843 4.77-10.996 10.712L15 19v9h22v-9c0-6.075-4.925-11-11-11z" />
    </svg> </span>) or <strong>https://</strong> means you’ve safely connected to
    the .gov website. Share sensitive information only on official,
    secure websites.'
alerts:
  status: Informative status
  text: Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod.
search:
  label: Search
